import { ResearchReport, Flashcard } from "../types";

export function generateMarkdownReport(report: ResearchReport): string {
    const authorName = process.env.AUTHOR_NAME || "Mohamed Al Hamdhy";
    const githubUser = process.env.GITHUB_USERNAME || "mohamedalhamdhy";

    const lines: string[] = [];

    lines.push(`# 📚 Research Report: ${report.title}`);
    lines.push("");
    lines.push(`> Generated by [LEARNSYS](https://github.com/${githubUser}/learnsys) on ${new Date(report.processedAt).toLocaleString()}`);
    lines.push(`> **Source:** ${report.source} | **Type:** ${report.sourceType.toUpperCase()} | **Words:** ${report.wordCount.toLocaleString()}`);
    lines.push("");
    lines.push("## 📋 Table of Contents");
    lines.push("- [Summary](#summary)");
    lines.push("- [Key Points](#key-points)");
    lines.push("- [Actionable Insights](#actionable-insights)");
    lines.push("- [Keywords & Concepts](#keywords--concepts)");
    lines.push("- [Sections Overview](#sections-overview)");
    lines.push("- [Flashcards](#flashcards)");
    if (report.citations.length > 0) lines.push("- [Citations](#citations)");
    lines.push("");
    lines.push("## 📝 Summary");
    lines.push("");
    lines.push(report.summary);
    lines.push("");
    lines.push("## 🎯 Key Points");
    lines.push("");
    for (const kp of report.keyPoints) {
        lines.push(`- ${kp}`);
    }
    lines.push("");

    lines.push("## 💡 Actionable Insights");
    lines.push("");
    for (const ai of report.actionableInsights) {
        lines.push(`- ✅ ${ai}`);
    }
    lines.push("");

    lines.push("## 🔑 Keywords & Concepts");
    lines.push("");
    lines.push("| Keyword | Frequency | Importance |");
    lines.push("|---------|-----------|------------|");
    for (const kw of report.keywords.slice(0, 15)) {
        const bar = "█".repeat(Math.round(kw.importance / 10)) + "░".repeat(10 - Math.round(kw.importance / 10));
        lines.push(`| **${kw.term}** | ${kw.frequency} | ${bar} ${kw.importance}% |`);
    }
    lines.push("");

    if (report.sections.length > 0) {
        lines.push("## 📖 Sections Overview");
        lines.push("");
        for (const s of report.sections) {
            lines.push(`### ${s.title}`);
            lines.push(`*${s.wordCount} words*`);
            lines.push("");
            if (s.summary) lines.push(s.summary);
            else lines.push(s.content.substring(0, 300) + (s.content.length > 300 ? "..." : ""));
            lines.push("");
        }
    }

    lines.push("## 🃏 Flashcards");
    lines.push("");
    for (let i = 0; i < report.flashcards.length; i++) {
        const fc = report.flashcards[i];
        const diffEmoji = { easy: "🟢", medium: "🟡", hard: "🔴" }[fc.difficulty] || "⚪";
        lines.push(`### Card ${i + 1} ${diffEmoji}`);
        lines.push(`**Q:** ${fc.question}`);
        lines.push(`**A:** ${fc.answer}`);
        if (fc.tags.length > 0) lines.push(`*Tags: ${fc.tags.join(", ")}*`);
        lines.push("");
    }

    if (report.citations.length > 0) {
        lines.push("## 📎 Citations");
        lines.push("");
        for (const c of report.citations) {
            lines.push(`- ${c.authors}${c.year ? ` (${c.year})` : ""}${c.title ? `. ${c.title}` : ""}`);
        }
        lines.push("");
    }

    lines.push("---");
    lines.push(`*Generated by [LEARNSYS](https://github.com/${githubUser}/learnsys) — Research Automation by ${authorName}*`);

    return lines.join("\n");
}

export function generateCSVFlashcards(flashcards: Flashcard[]): string {
    const header = "id,question,answer,difficulty,tags,confidence";
    const rows = flashcards.map(fc => [
        fc.id,
        `"${fc.question.replace(/"/g, '""')}"`,
        `"${fc.answer.replace(/"/g, '""')}"`,
        fc.difficulty,
        `"${fc.tags.join(";")}"`,
        fc.confidence,
    ].join(","));
    return [header, ...rows].join("\n");
}

export function generateAnkiExport(flashcards: Flashcard[], deckName: string): string {
    const lines: string[] = [
        "#separator:tab",
        "#html:false",
        `#deck:${deckName}`,
        "#notetype:Basic",
        "",
    ];
    for (const fc of flashcards) {
        lines.push(`${fc.question}\t${fc.answer}\t${fc.tags.join(" ")}`);
    }
    return lines.join("\n");
}

export function generateQuizletExport(flashcards: Flashcard[]): string {
    return flashcards.map(fc => `${fc.question}|${fc.answer}`).join("\n");
}

export function calcReadabilityScore(text: string): number {
    const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 5);
    const words = text.split(/\s+/).filter(Boolean);
    const avgWordsPerSentence = words.length / Math.max(sentences.length, 1);
    const avgCharsPerWord = text.replace(/\s/g, "").length / Math.max(words.length, 1);

    const score = 100 - (avgWordsPerSentence * 1.5) - (avgCharsPerWord * 3);
    return Math.max(0, Math.min(100, Math.round(score)));
}

export function calcComplexityScore(text: string, keywords: { term: string }[]): number {
    const technicalTerms = keywords.filter(k => k.term.includes("-") || k.term.length > 12).length;
    const avgWordLen = text.replace(/\s/g, "").length / Math.max(text.split(/\s+/).length, 1);
    const score = Math.min(100, technicalTerms * 3 + avgWordLen * 5);
    return Math.round(score);
}